
public class adminmenu extends javax.swing.JFrame {

    /**
     * Creates new form adminmenu
     */
    public adminmenu() {
        initComponents();
        setTitle("ADMIN MENU");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        badminmenudelprod = new javax.swing.JButton();
        badminmenuupdateprod = new javax.swing.JButton();
        badminmenulogout = new javax.swing.JButton();
        badminmenupurchasehistory = new javax.swing.JButton();
        badminmenuuserdetail = new javax.swing.JButton();
        badminmenuaddprod = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        badminmenudelprod.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        badminmenudelprod.setText("DELETE PRODUCT");
        badminmenudelprod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                badminmenudelprodMouseClicked(evt);
            }
        });
        badminmenudelprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                badminmenudelprodActionPerformed(evt);
            }
        });

        badminmenuupdateprod.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        badminmenuupdateprod.setText("UPDATE PRODUCT");
        badminmenuupdateprod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                badminmenuupdateprodMouseClicked(evt);
            }
        });
        badminmenuupdateprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                badminmenuupdateprodActionPerformed(evt);
            }
        });

        badminmenulogout.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        badminmenulogout.setText("LOGOUT");
        badminmenulogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                badminmenulogoutMouseClicked(evt);
            }
        });

        badminmenupurchasehistory.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        badminmenupurchasehistory.setText("PURCHASE HISTORY");
        badminmenupurchasehistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                badminmenupurchasehistoryMouseClicked(evt);
            }
        });
        badminmenupurchasehistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                badminmenupurchasehistoryActionPerformed(evt);
            }
        });

        badminmenuuserdetail.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        badminmenuuserdetail.setText("USER DETAIL");
        badminmenuuserdetail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                badminmenuuserdetailMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(badminmenuupdateprod)
                            .addComponent(badminmenudelprod)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(badminmenupurchasehistory)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(148, 228, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(badminmenulogout)
                        .addGap(246, 246, 246))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(badminmenuuserdetail)
                        .addGap(223, 223, 223))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(badminmenudelprod)
                .addGap(43, 43, 43)
                .addComponent(badminmenuupdateprod)
                .addGap(45, 45, 45)
                .addComponent(badminmenupurchasehistory)
                .addGap(48, 48, 48)
                .addComponent(badminmenuuserdetail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(badminmenulogout)
                .addContainerGap())
        );

        badminmenuaddprod.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        badminmenuaddprod.setText("ADD PRODUCT");
        badminmenuaddprod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                badminmenuaddprodMouseClicked(evt);
            }
        });
        badminmenuaddprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                badminmenuaddprodActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(badminmenuaddprod)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(badminmenuaddprod)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void badminmenudelprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_badminmenudelprodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_badminmenudelprodActionPerformed

    private void badminmenuaddprodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_badminmenuaddprodMouseClicked
        // TODO add your handling code here:
        add ad = new add();
        ad.setVisible(true);
        setVisible(false);
        
        
    }//GEN-LAST:event_badminmenuaddprodMouseClicked

    private void badminmenudelprodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_badminmenudelprodMouseClicked
        // TODO add your handling code here:
        delete del = new delete();
        del.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_badminmenudelprodMouseClicked

    private void badminmenuupdateprodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_badminmenuupdateprodMouseClicked
        // TODO add your handling code here:
        update up = new update();
        up.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_badminmenuupdateprodMouseClicked

    private void badminmenulogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_badminmenulogoutMouseClicked
        // TODO add your handling code here:
        adminlogin al = new adminlogin();
        al.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_badminmenulogoutMouseClicked

    private void badminmenuaddprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_badminmenuaddprodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_badminmenuaddprodActionPerformed

    private void badminmenuupdateprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_badminmenuupdateprodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_badminmenuupdateprodActionPerformed

    private void badminmenupurchasehistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_badminmenupurchasehistoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_badminmenupurchasehistoryActionPerformed

    private void badminmenuuserdetailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_badminmenuuserdetailMouseClicked
        // TODO add your handling code here:
        userdetail ud = new userdetail();
        ud.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_badminmenuuserdetailMouseClicked

    private void badminmenupurchasehistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_badminmenupurchasehistoryMouseClicked
        // TODO add your handling code here:
        purchasehistory ph = new purchasehistory();
        ph.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_badminmenupurchasehistoryMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminmenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton badminmenuaddprod;
    private javax.swing.JButton badminmenudelprod;
    private javax.swing.JButton badminmenulogout;
    private javax.swing.JButton badminmenupurchasehistory;
    private javax.swing.JButton badminmenuupdateprod;
    private javax.swing.JButton badminmenuuserdetail;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
