
import java.sql.*;
    import javax.swing.*;
import java.time.*;
import java.time.format.DateTimeFormatter;
import javax.swing.table.DefaultTableModel;
public class bill extends javax.swing.JFrame{

    /**
     * Creates new form bill
     */
    int price = 0;
    public bill() {
        initComponents();
        setTitle("INVOICE");
        
        
        
    }
    String pass;
   

    bill(String id, String name) {
        initComponents();
        this.pass=id;
        tbilluserid.setText(id);
        tbilluserid.setEditable(false);
        tbillusername.setText(name);
        tbillusername.setEditable(false);
        
       // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tbillperprice = new javax.swing.JTextField();
        cbillprodname = new javax.swing.JComboBox<>();
        tbillquantity = new javax.swing.JTextField();
        tbillprice = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        billtable = new javax.swing.JTable();
        bbilladd = new javax.swing.JButton();
        bbillupdate = new javax.swing.JButton();
        bbillcancel = new javax.swing.JButton();
        bbillprint = new javax.swing.JButton();
        bbilllogout = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ibillinvoiceid = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tbillusername = new javax.swing.JTextField();
        tbilluserid = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tbilldate = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tbilltime = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("PRODUCT NAME");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("PRICE PER PIECE");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("QUANTITY");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("PRICE");

        tbillperprice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tbillperprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbillperpriceActionPerformed(evt);
            }
        });

        cbillprodname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cbillprodname.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mars", "Snickers", "Skittles", "cake", "chettos" }));
        cbillprodname.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cbillprodnamePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        cbillprodname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbillprodnameActionPerformed(evt);
            }
        });

        tbillquantity.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tbillquantity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tbillquantityFocusLost(evt);
            }
        });
        tbillquantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbillquantityActionPerformed(evt);
            }
        });

        tbillprice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tbillprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbillpriceActionPerformed(evt);
            }
        });

        billtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null,null,null}

            },
            new String [] {
                "INVOICE ID", "USER ID", "PRODUCT ID", "PRODUCT PRICE"
            }
        ));
        billtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                billtableMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(billtable);

        bbilladd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bbilladd.setText("ADD");
        bbilladd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bbilladdMouseClicked(evt);
            }
        });

        bbillupdate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bbillupdate.setText("UPDATE");
        bbillupdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bbillupdateMouseClicked(evt);
            }
        });
        bbillupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbillupdateActionPerformed(evt);
            }
        });

        bbillcancel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bbillcancel.setText("CANCEL");
        bbillcancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bbillcancelMouseClicked(evt);
            }
        });
        bbillcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbillcancelActionPerformed(evt);
            }
        });

        bbillprint.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bbillprint.setText("GENERATE");
        bbillprint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bbillprintMouseClicked(evt);
            }
        });
        bbillprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbillprintActionPerformed(evt);
            }
        });

        bbilllogout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bbilllogout.setText("LOGOUT");
        bbilllogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bbilllogoutMouseClicked(evt);
            }
        });
        bbilllogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbilllogoutActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("INVOICE");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("INVOICE ID");

        ibillinvoiceid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ibillinvoiceid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ibillinvoiceidFocusGained(evt);
            }
        });
        ibillinvoiceid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ibillinvoiceidActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("USERID");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("USERNAME");

        tbillusername.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tbillusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbillusernameActionPerformed(evt);
            }
        });

        tbilluserid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tbilluserid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbilluseridActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("PRODUCT ID");

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("DATE");

        tbilldate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tbilldate.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                tbilldateMouseMoved(evt);
            }
        });
        tbilldate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbilldateActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("TIME");

        tbilltime.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tbilltime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbilltimeActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel9)
                                .addComponent(jLabel10)
                                .addComponent(jLabel8))
                            .addComponent(jLabel3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bbilladd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bbillupdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bbillprint)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel11))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6)))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tbilldate, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                                    .addComponent(tbilltime))
                                .addGap(29, 29, 29))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tbillprice, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(bbillcancel)
                                        .addGap(18, 18, 18)
                                        .addComponent(bbilllogout)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tbillusername, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ibillinvoiceid, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbillprodname, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tbilluserid, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbillquantity, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbillperprice, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(tbilldate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tbilltime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(tbilluserid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(tbillperprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(tbillquantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(tbillprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(tbillusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(ibillinvoiceid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(cbillprodname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(142, 142, 142)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bbilladd)
                            .addComponent(bbillupdate)
                            .addComponent(bbillprint)
                            .addComponent(bbillcancel)
                            .addComponent(bbilllogout)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bbillupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbillupdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bbillupdateActionPerformed

    private void tbillperpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbillperpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbillperpriceActionPerformed

    private void tbillpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbillpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbillpriceActionPerformed

    private void bbillcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbillcancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bbillcancelActionPerformed

    private void bbilllogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbilllogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bbilllogoutActionPerformed

    private void tbillquantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbillquantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbillquantityActionPerformed

    private void ibillinvoiceidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ibillinvoiceidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ibillinvoiceidActionPerformed

    private void tbillusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbillusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbillusernameActionPerformed

    private void tbilluseridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbilluseridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbilluseridActionPerformed

    private void cbillprodnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbillprodnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbillprodnameActionPerformed

    private void bbillprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbillprintActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bbillprintActionPerformed

    private void cbillprodnamePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cbillprodnamePopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        Connection conn=jdbcConnection.connect();
        String prod = (String) cbillprodname.getSelectedItem();
        String sql = "select *  from product where productname=?";
        
        try{
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, prod);
            ResultSet rs = ps.executeQuery();
            if(rs.next())
            {
                String p = rs.getString("productprice");
                String id = rs.getString("productid");
                jTextField1.setText(id);
                
                tbillperprice.setText(p);
                tbillperprice.setEditable(false);
                price = Integer.parseInt(p);
                tbillquantityFocusLost(price);
            }
           
            
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_cbillprodnamePopupMenuWillBecomeInvisible

    private void tbillquantityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tbillquantityFocusLost
        // TODO add your handling code here:
         int qty= Integer.parseInt(tbillquantity.getText());
            int tot= price * qty;
            String total = Integer.toString(tot);
            tbillprice.setText(total);
            tbillprice.setEditable(false);
    }//GEN-LAST:event_tbillquantityFocusLost

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void bbillcancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bbillcancelMouseClicked
        // TODO add your handling code here:
        jTextField1.setText("");
        tbilluserid.setText("");
        tbillusername.setText("");
        ibillinvoiceid.setText("");
        tbillperprice.setText("");
        tbillquantity.setText("");
        tbillprice.setText("");
        
        
    }//GEN-LAST:event_bbillcancelMouseClicked

    private void bbilllogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bbilllogoutMouseClicked
        // TODO add your handling code here:
        userlogin ul = new userlogin();
        ul.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_bbilllogoutMouseClicked

    private void bbilladdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bbilladdMouseClicked
        // TODO add your handling code here:
        Connection conn = jdbcConnection.connect();
        String sql="insert into bill values(?,?,?,?,?,?)";
        try{
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, ibillinvoiceid.getText());
            ps.setString(2,tbilluserid.getText());
            ps.setString(3, jTextField1.getText());
            ps.setString(4, tbillprice.getText());
            ps.setString(5,tbilldate.getText());
            ps.setString(6,tbilltime.getText());
            
            int count = ps.executeUpdate();
             if(count >0){
                    JOptionPane.showMessageDialog(null,"DATA INSERTED SUCCESSFULLY");
             }
             else{
                 JOptionPane.showMessageDialog(null,"DATA INSERTED UNSUCCESSFUL");
             }
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
       
    }//GEN-LAST:event_bbilladdMouseClicked

    private void bbillupdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bbillupdateMouseClicked
        // TODO add your handling code here:
          Connection conn=null;
        conn=jdbcConnection.connect();
        String sql="update bill set userid = ?, productid = ? ,price= ? , date=?, time=? where invoiceid = ? and productid=?";
        try{
        PreparedStatement ps = conn.prepareStatement(sql);
       
            ps.setString(1,tbilluserid.getText());
            ps.setString(2, jTextField1.getText());
            ps.setString(3, tbillprice.getText());
             ps.setString(6, ibillinvoiceid.getText());
             ps.setString(4,tbilldate.getText());
             ps.setString(5,tbilltime.getText());
             ps.setString(7, jTextField1.getText());
        int temp = ps.executeUpdate();
            
        if(temp>0)
        {
            JOptionPane.showMessageDialog(null,"UPDATION SUCCESSFUL");
        }
        else{
            JOptionPane.showMessageDialog(null, "UPDATION UNSUCCESSFUL");
        }
        ResultSet rs = ps.executeQuery();
        
       
        }catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_bbillupdateMouseClicked

    private void billtableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billtableMouseEntered
        // TODO add your handling code here:
        Connection conn=jdbcConnection.connect();
        String sql ="select * from bill";
        try{
            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            DefaultTableModel dtm=(DefaultTableModel)billtable.getModel();
            dtm.insertRow(dtm.getRowCount(), new Object[]{ibillinvoiceid.getText(),tbilluserid.getText(),jTextField1.getText(),tbillprice.getText()});
               
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_billtableMouseEntered

    private void tbilldateMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbilldateMouseMoved
        // TODO add your handling code here:
    
    }//GEN-LAST:event_tbilldateMouseMoved

    private void tbilldateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbilldateActionPerformed
        // TODO add your handling code here:
      
         
    }//GEN-LAST:event_tbilldateActionPerformed

    private void ibillinvoiceidFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ibillinvoiceidFocusGained
        // TODO add your handling code here:
          LocalDate date=java.time.LocalDate.now();
        tbilldate.setText(date.toString());
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("HH:mm");
        LocalTime now = LocalTime.now();
        String timeString= now.format(formatter);
        tbilltime.setText(timeString);
    }//GEN-LAST:event_ibillinvoiceidFocusGained

    private void tbilltimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbilltimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbilltimeActionPerformed

    private void bbillprintMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bbillprintMouseClicked
        // TODO add your handling code here:
        String uid = String.format(tbilluserid.getText());
        String date = String.format(tbilldate.getText());
        String time = String.format(tbilltime.getText());
        String uname= String.format(tbillusername.getText());
        String iid=String.format(ibillinvoiceid.getText());
        String pname = String.valueOf(cbillprodname.getSelectedItem());
        String pid = String.format(jTextField1.getText());
        String price = String.format(tbillperprice.getText());
        String qty = String.format(tbillquantity.getText());
        String total = String.format(tbillprice.getText());
        
        jTextArea1.append("***************INVOICE****************\n******************************************\nUSER ID:"+uid+"                                                   DATE:"+date+"\nUSER NAME:"+uname+"                                       TIME:"+time+"\nINVOICE ID:"+iid+"\nPRODUCT NAME:"+pname+"\nPRODUCT ID:"+pid+"\nPRICE PER PIECE:"+price+"\nQUANTITY:"+qty+"\nTOTAL:"+total);
        
        
        
        
    }//GEN-LAST:event_bbillprintMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bbilladd;
    private javax.swing.JButton bbillcancel;
    private javax.swing.JButton bbilllogout;
    private javax.swing.JButton bbillprint;
    private javax.swing.JButton bbillupdate;
    private javax.swing.JTable billtable;
    private javax.swing.JComboBox<String> cbillprodname;
    private javax.swing.JTextField ibillinvoiceid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField tbilldate;
    private javax.swing.JTextField tbillperprice;
    private javax.swing.JTextField tbillprice;
    private javax.swing.JTextField tbillquantity;
    private javax.swing.JTextField tbilltime;
    private javax.swing.JTextField tbilluserid;
    private javax.swing.JTextField tbillusername;
    // End of variables declaration//GEN-END:variables

    private void tbillquantityFocusLost(int price) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
