
import java.sql.*;
import javax.swing.*;
public class form extends javax.swing.JFrame {

    /**
     * Creates new form form
     */
    public form() {
        initComponents();
        setTitle("USER SIGNIN FORM");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tformid = new javax.swing.JTextField();
        tformfirstname = new javax.swing.JTextField();
        tformphone = new javax.swing.JTextField();
        tformaddress = new javax.swing.JTextField();
        tformmail = new javax.swing.JTextField();
        bformback = new javax.swing.JButton();
        bformsubmit = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        tformlastname = new javax.swing.JTextField();
        tformpassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("SIGN IN FORM");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("USER ID");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("FIRST NAME");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("PHONE");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("ADDRESS");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("EMAIL ID");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("PASSWORD");

        tformid.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tformid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tformidActionPerformed(evt);
            }
        });

        tformfirstname.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tformfirstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tformfirstnameActionPerformed(evt);
            }
        });

        tformphone.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tformphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tformphoneActionPerformed(evt);
            }
        });

        tformaddress.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tformaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tformaddressActionPerformed(evt);
            }
        });

        tformmail.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tformmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tformmailActionPerformed(evt);
            }
        });

        bformback.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bformback.setText("BACK");
        bformback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bformbackMouseClicked(evt);
            }
        });

        bformsubmit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bformsubmit.setText("SUBMIT");
        bformsubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bformsubmitMouseClicked(evt);
            }
        });
        bformsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bformsubmitActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("LAST NAME");

        tformlastname.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tformlastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tformlastnameActionPerformed(evt);
            }
        });

        tformpassword.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tformpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tformpasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel4))
                .addGap(141, 141, 141)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tformaddress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                    .addComponent(tformphone)
                    .addComponent(tformfirstname, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tformid, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tformmail, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tformlastname)
                    .addComponent(tformpassword))
                .addGap(91, 91, 91))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(bformback)
                        .addGap(97, 97, 97)
                        .addComponent(bformsubmit)))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tformid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tformfirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tformlastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tformphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tformaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(tformmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tformpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bformback)
                    .addComponent(bformsubmit))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tformfirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tformfirstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tformfirstnameActionPerformed

    private void tformmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tformmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tformmailActionPerformed

    private void bformsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bformsubmitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bformsubmitActionPerformed

    private void tformphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tformphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tformphoneActionPerformed

    private void bformbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bformbackMouseClicked
        // TODO add your handling code here:
        user u = new user();
        u.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_bformbackMouseClicked

    private void tformidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tformidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tformidActionPerformed

    private void tformaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tformaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tformaddressActionPerformed

    private void tformlastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tformlastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tformlastnameActionPerformed

    private void bformsubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bformsubmitMouseClicked
        // TODO add your handling code here:
        Connection conn=null;
        conn=jdbcConnection.connect();
        String sql = " insert into user_detail values(?,?,?,?,?,?,?) ";
        try{
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setInt(1,Integer.parseInt(tformid.getText()));
            ps.setString(2,tformfirstname.getText());
            ps.setString(3, tformlastname.getText());
            ps.setString(4,tformphone.getText());
            ps.setString(5,tformaddress.getText());
            ps.setString(6, tformmail.getText());
            ps.setString(7,tformpassword.getText());
            
             int count = ps.executeUpdate();
            
             if(count >0){
                    JOptionPane.showMessageDialog(null,"DATA INSERTED SUCCESSFULLY");
             }
             else{
                 JOptionPane.showMessageDialog(null,"DATA INSERTED UNSUCCESSFUL");
             }
             
             tformid.setText("");
             tformfirstname.setText("");
             tformlastname.setText("");
             tformphone.setText("");
             tformaddress.setText("");
             tformmail.setText("");
             tformpassword.setText("");
             
            
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_bformsubmitMouseClicked

    private void tformpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tformpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tformpasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bformback;
    private javax.swing.JButton bformsubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tformaddress;
    private javax.swing.JTextField tformfirstname;
    private javax.swing.JTextField tformid;
    private javax.swing.JTextField tformlastname;
    private javax.swing.JTextField tformmail;
    private javax.swing.JPasswordField tformpassword;
    private javax.swing.JTextField tformphone;
    // End of variables declaration//GEN-END:variables
}
