
public class user extends javax.swing.JFrame {

    /**
     * Creates new form user
     */
    public user() {
        initComponents();
        setSize(300,300);
        setTitle("USER MENU");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        busersignup = new javax.swing.JButton();
        buserlogin = new javax.swing.JButton();
        buserback = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        busersignup.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        busersignup.setText("SIGN UP");
        busersignup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                busersignupMouseClicked(evt);
            }
        });
        busersignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busersignupActionPerformed(evt);
            }
        });

        buserlogin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        buserlogin.setText("LOGIN");
        buserlogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buserloginMouseClicked(evt);
            }
        });

        buserback.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        buserback.setText("BACK");
        buserback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buserbackMouseClicked(evt);
            }
        });
        buserback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buserbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(buserlogin)
                .addGap(51, 51, 51))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(busersignup)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(buserback)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(buserlogin)
                .addGap(39, 39, 39)
                .addComponent(busersignup)
                .addGap(44, 44, 44)
                .addComponent(buserback)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void busersignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busersignupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_busersignupActionPerformed

    private void buserbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buserbackActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_buserbackActionPerformed

    private void buserloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buserloginMouseClicked
        // TODO add your handling code here:
        userlogin ul = new userlogin();
        ul.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_buserloginMouseClicked

    private void busersignupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_busersignupMouseClicked
        // TODO add your handling code here:
        form f= new form();
        f.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_busersignupMouseClicked

    private void buserbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buserbackMouseClicked
        // TODO add your handling code here:
        welcome w = new welcome();
        w.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_buserbackMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new user().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buserback;
    private javax.swing.JButton buserlogin;
    private javax.swing.JButton busersignup;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
